services:
  - type: web
    name: gstockboncoin
    runtime: docker
    branch: master
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: GStockBoncoin
      - key: APP_ENV
        value: production
      - key: APP_URL
        value: https://gstockboncoin.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
